. ~/projects/everyman/.bash_aliases
. ~/projects/webnorris/.bash_aliases
. ~/projects/newiebewies/.bash_aliases
. ~/projects/carprogramming/.bash_aliases
. ~/projects/fourmuxiwuxies/.bash_aliases
. ~/projects/aliasbusiness/.bash_aliases
. ~/projects/maam/.bash_aliases
. ~/projects/duckduckgo/.bash_aliases
. ~/projects/gitsywitsies/.bash_aliases
. ~/projects/findstuff/.bash_aliases
. ~/projects/keyremaps/.bash_aliases
. ~/projects/neovimbashiewashies/.bash_aliases
. ~/projects/miscywhiskies/.bash_aliases
