. ~/projects/bashshit/everyman/.bash_aliases
. ~/projects/bashshit/webnorris/.bash_aliases
. ~/projects/bashshit/newiebewies/.bash_aliases
. ~/projects/bashshit/carprogramming/.bash_aliases
. ~/projects/bashshit/fourmuxiwuxies/.bash_aliases
. ~/projects/bashshit/aliasbusiness/.bash_aliases
. ~/projects/bashshit/maam/.bash_aliases
. ~/projects/bashshit/duckduckgo/.bash_aliases
. ~/projects/bashshit/gitsywitsies/.bash_aliases
. ~/projects/bashshit/findstuff/.bash_aliases
. ~/projects/bashshit/keyremaps/.bash_aliases
. ~/projects/bashshit/neovimbashiewashies/.bash_aliases
. ~/projects/bashshit/miscywhiskies/.bash_aliases
